### ISSUE TITLE
Custom ladder

### ISSUE THREAD

**Issue by hsgweon** [rickud/gel-lanes-fit#10]
Many thanks for this very cool tool which I installed and managed to play with my gel images. I have a quick question. The tool currently only supports two ladders (Hi-Lo from Bionexus and 100bp ladder from NEB). Is there a possibility of adding more ladders? For example NEB's ["Quick-Load® 1 kb Extend DNA Ladder"](https://international.neb.com/products/n3239-quick-load-1kb-extend-dna-ladder#Product%20Information)? The ladder composition and a list of the bp lengths and mass are in that link. Thank you!

**Comment by melop** [comment]
Hello, we use a non-standard ladder with the following bands: 2kb, 1kb, 750bp, 500bp, 200bp and 100bp. Is there a way to let the user edit the peak standards, or perhaps provide a text file describing the ladder? It doesn't seem to be convenient to hard-code this in the code?
