### ISSUE TITLE
Trouble running plugin

### ISSUE THREAD

**Issue by majdabdul** [rickud/gel-lanes-fit#12]
Dear Rick,

First I want to thank you for the effort you put into this tool. I think it's really valuable that such an option is available for those who cannot access the BioAnalyzer, TapeStation, or similar systems, which are insanely priced. Thank you so much.

Second, can you kindly help me figure out why I'm unable to run the tool? I'm not sure if the issue is with Fiji or with how I'm installing the plugin, but here's a breakdown of what's happening:

1. I downloaded the latest version of Fiji (v1.53h).
2. I downloaded the latest release of Gel Lanes Fit (gel-lanes-fit-1.0.6.jar)
3. I opened Fiji and went to Plugins > Install Plugin.... This is were I encountered the first issue. Clicking 'Install Plugin...' does nothing at all.
4. So, I instead went to Plugins > Install... and I selected the .jar file.
5. I restarted Fiji and checked for the plugin under Gel Tools. It was not there.

I tried using old school ImageJ (v1) instead, but it didn't make a difference, I still couldn't find the plugin in the Gel Tools submenu.

I can see after I install the plugin that a copy of it is made in a folder called 'jars' inside the Plugins folder of Fiji and ImageJ, but for some reason it won't be incorporated into the interface.

I would really appreciate your help.

**Comment by majdabdul** [comment]
Sorry, for some reason, the plugin was installed under a different name. It was called DoNALD. I hadn't thought to try it before because I was expecting 'Gel Lanes Fit' to appear in the 'Gel Tools' menu, but what was there instead was 'DoNALD'. When I clicked that, I got the gel lanes fit windows. Thanks Rick!

**Comment by rickud** [comment]
Yes, apologies for the confusion. The name was a _phase_ we went through. It will revert back to the original name. Let us know if there are any other issues we can help with.
